# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algo_args.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61lgo_args.proto\"_\n\tAlgoInput\x12$\n\x05iargs\x18\x01 \x03(\x0b\x32\x15.AlgoInput.IargsEntry\x1a,\n\nIargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"a\n\nAlgoOutput\x12%\n\x05oargs\x18\x01 \x03(\x0b\x32\x16.AlgoOutput.OargsEntry\x1a,\n\nOargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algo_args_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALGOINPUT_IARGSENTRY._options = None
  _ALGOINPUT_IARGSENTRY._serialized_options = b'8\001'
  _ALGOOUTPUT_OARGSENTRY._options = None
  _ALGOOUTPUT_OARGSENTRY._serialized_options = b'8\001'
  _ALGOINPUT._serialized_start=19
  _ALGOINPUT._serialized_end=114
  _ALGOINPUT_IARGSENTRY._serialized_start=70
  _ALGOINPUT_IARGSENTRY._serialized_end=114
  _ALGOOUTPUT._serialized_start=116
  _ALGOOUTPUT._serialized_end=213
  _ALGOOUTPUT_OARGSENTRY._serialized_start=169
  _ALGOOUTPUT_OARGSENTRY._serialized_end=213
# @@protoc_insertion_point(module_scope)
